<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="css/normalize.css">
	<link rel="stylesheet" type="text/css" href="css/style.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
	<meta charset="utf-8">
	<title>Mon super blog</title>
	<script src="js/script.js"></script>
</head>
<body>
	<?php include ('header.phtml');?>
	<main>
		 
        <section>   
            
            <?php foreach($posts as $post): ?>

            	<article>
                <h1> #Article</h1>
                <h2><?= $post['title'] ?></h2>
                <p><a href="detail.php?id=<?= $post['id'] ?>"><?= substr($post['content'],0,200) ?></a></p>
               
                </article>

               
                
            <?php endforeach ?>
        </section>          
	</main>
	
	<?php  include('footer.phtml'); ?>

</body>
</html>

